version: "3"
services:
    database:
        image: 'postgres'
        container_name: "${HOST}"
        env_file:
            - .env 
        ports:
            - "5557:5557"
        expose:
            - 5557 
        volumes:
            - ./db:/var/lib/postresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    backend:
        container_name: diary_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: jviitamo/server
        env_file:
            - .env
        ports:
            - "3003:3003"
        volumes:
            - ./server:/usr/src/app
            - ./frontend/public/photos:/usr/src/app/temp_uploads
            - /usr/src/app/node_modules
    frontend:
        container_name: diary_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: jviitamo/frontend
        environment:
            VUE_APP_API_URL: "${API_URL}"
        ports:
            - "8081:8081"
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules

