name: Main Workflow
on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          config-file: cypress.config.js
          build: npm run build
          start: npm run serve

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: testing ssh
      uses: appleboy/ssh-action@master
      with:
        host: juhanaviitamo.fi
        username: jviitamo 
        key: ${{ secrets.DEPLOYMENT_SECRET }} 
        port: 22
        script: |
          cd diary
          git pull origin main
          docker-compose up --build -d