name: Main Workflow
on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          config-file: cypress.config.js
          build: npm run build
          start: npm run serve

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: testing ssh
      uses: appleboy/ssh-action@master
      with:
        host: juhanaviitamo.fi
        username: jviitamo 
        key: ${{ secrets.DEPLOYMENT_SECRET }} 
        port: 22
        script: |
          cd diary
          git pull origin main
          docker-compose up --build -d
 
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2
      
      - name: Build docker images
      - run: |
        run: docker build . -t 040100/diary:server -f ./server/Dockerfile 
        run: docker build . -t 040100/diary:frontend -f ./frontend/Dockerfile 
        run: docker build . -t 040100/diary:database -f ./database/Dockerfile 


      - name: Push docker images
      - run: |
          docker image push 040100/diary:server
          docker image push 040100/diary:frontend
          docker image push 040100/diary:database

      
    